
  CREATE TABLE "SCOTT"."USER_AUTH" 
   (	"USERNAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"AUTHORITY" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 FOREIGN KEY ("USERNAME")
	  REFERENCES "SCOTT"."USER_DETAILS" ("USERNAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "SCOTT"."USER_DETAILS" 
   (	"USERNAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

Insert into USER_AUTH (USERNAME,AUTHORITY) values ('user','ROLE_USER');
Insert into USER_AUTH (USERNAME,AUTHORITY) values ('admin','ROLE_ADMIN');


Insert into USER_DETAILS (USERNAME,PASSWORD) values ('user','123');
Insert into USER_DETAILS (USERNAME,PASSWORD) values ('admin','admin');
